package ru.otus.msa.user.api;

public enum BillingEventStatus {
    DEPOSIT_PAID,
    DEPOSIT_PAYMENT_REJECTED,
    DEPOSIT_RETURN_REJECT,
    DEPOSIT_RETURNED,
    DEPOSIT_MANAGER_ACCRUED,
    DEPOSIT_MANAGER_ACCRUED_ERROR,
    PRODUCT_PAID,
    PRODUCT_PAYMENT_REJECTED
}
