{
 "title": "otus-msa-user-service-board",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Среднее время ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_seconds_sum{uri=\"/api/users\",service=\"userservice-user-service-chart\"}[2m])) / (sum by(method, uri) (rate(http_server_requests_seconds_count{service=\"userservice-user-service-chart\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Response Time) (le 0.95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(http_server_requests_seconds_bucket{service=\"userservice-user-service-chart\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Response Time) (le 0.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method) (rate(http_server_requests_seconds_bucket{service=\"userservice-user-service-chart\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Response Time) (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max(rate(http_server_requests_seconds_sum{service=\"userservice-user-service-chart\"}[5m])) by (method) / max(rate(http_server_requests_seconds_count{service=\"userservice-user-service-chart\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Response Time) (le 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(http_server_requests_seconds_bucket{service=\"userservice-user-service-chart\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(method, uri, status, outcome) \r\n(rate(http_server_requests_seconds_count{service=\"userservice-user-service-chart\", outcome=~\".*_ERROR\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": " sum by(method) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}