apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.projectNamespace }}
type: Opaque
data:
  spring.datasource.password: cG9zdGdyZXM=
  keycloak.credentials.secret: akFQU3YxQ1c1b2VIRFpqRGc1eHlZNElyeFVDbEh0cEg=